export const APPEARANCE_SET_TAB_BAR_VISIBLE = 'APPEARANCE_SET_TAB_BAR_VISIBLE'

export const STORE_RESET = 'STORE_RESET';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_SET_INITIALIZED = 'AUTH_SET_INITIALIZED';
export const AUTH_SET_ERROR = 'AUTH_SET_ERROR';
export const AUTH_SET_LOGGED_IN = 'AUTH_SET_LOGGED_IN';

export const CUSTOMER_SET_PAYMENT_METHODS = 'CUSTOMER_SET_PAYMENT_METHODS';
export const CUSTOMER_SET_PAYMENT_METHODS_LOADED = 'CUSTOMER_SET_PAYMENT_METHODS_LOADED';
export const CUSTOMER_SET_PAYMENT_METHODS_LOADING = 'CUSTOMER_SET_PAYMENT_METHODS_LOADING';
export const CUSTOMER_SELECT_PAYMENT_METHOD = 'CUSTOMER_SELECT_PAYMENT_METHOD';

export const CUSTOMER_SET_RECENT_ADDRESSES = "CUSTOMER_SET_RECENT_ADDRESSES"
export const CUSTOMER_SET_SAVED_ADDRESSES = "CUSTOMER_SET_SAVED_ADDRESSES"
export const CUSTOMER_SET_SELECTED_ADDRESS= "CUSTOMER_SET_SELECTED_ADDRESS"

export const CUSTOMER_SET_CONTACTS_LOADED = "CUSTOMER_SET_CONTACTS_LOADED"
export const CUSTOMER_SET_CONTACTS_LIST = "CUSTOMER_SET_CONTACTS_LIST"

export const CUSTOMER_SET_ORDERS = "CUSTOMER_SET_ORDERS"
export const CUSTOMER_SET_ORDER = "CUSTOMER_SET_ORDER"
export const CUSTOMER_ADD_NEW_ORDER = "CUSTOMER_ADD_NEW_ORDER"
export const CUSTOMER_UPDATE_ORDER = "CUSTOMER_UPDATE_ORDER"
export const CUSTOMER_SET_ORDERS_LOADED = "CUSTOMER_SET_ORDERS_LOADED"
export const CUSTOMER_SET_ORDERS_LOADING = "CUSTOMER_SET_ORDERS_LOADING"

export const CUSTOMER_ORDER_CHAT_SET_LIST = 'APP_ORDER_CHAT_SET_LIST'

export const APP_SET_FAQS = 'APP_SET_FAQS'

export const APP_LOCATION_SET_AVAILABLE = 'APP_LOCATION_SET_AVAILABLE'
export const APP_LOCATION_SET_CURRENT = 'APP_LOCATION_SET_CURRENT'

export const CURRENT_LANG = 'CURRENT_LANG'
